# Generated by Django 3.2.16 on 2022-11-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=16, verbose_name='Course ID')),
                ('title', models.CharField(max_length=64, verbose_name='Course Title')),
                ('semester', models.CharField(max_length=32, verbose_name='Semester')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=128, verbose_name='Proposal Id')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.teacher', verbose_name='Assigned By')),
                ('assigned_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_proposals', to='accounts.teacher', verbose_name='Assigned Supervisor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_management.course')),
                ('preferred_supervisors', models.ManyToManyField(related_name='proposals', to='accounts.Teacher', verbose_name='Preferred Supervisor')),
                ('students', models.ManyToManyField(related_name='proposal', to='accounts.Student', verbose_name='Students')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_submitted', to='accounts.student', verbose_name='Submitted By')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.student', verbose_name='Team Lead')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(max_length=32, verbose_name='Total Marks')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='project_management.proposal', verbose_name='Proposal Name')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='accounts.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marksheets', to='project_management.proposal', verbose_name='Proposals')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marksheets', to='accounts.student', verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marksheets', to='accounts.teacher', verbose_name='Teacher')),
            ],
        ),
    ]
