# Generated by Django 3.2.16 on 2022-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='criteria_1',
            field=models.CharField(default=dict, max_length=128, verbose_name='Criteria 1 Mark'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='criteria_2',
            field=models.CharField(default=0, max_length=128, verbose_name='Criteria 2 Mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheet',
            name='supervisor',
            field=models.CharField(default=0, max_length=128, verbose_name='Supervisor Mark'),
            preserve_default=False,
        ),
    ]
