# Generated by Django 3.2.16 on 2022-11-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_teacher'),
        ('project_management', '0004_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='assigned_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_proposals', to='accounts.teacher', verbose_name='Assigned Supervisor'),
        ),
    ]
