# Generated by Django 3.2.16 on 2022-11-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_remove_proposal_proposal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='file',
            field=models.FileField(default=1, upload_to='proposals/'),
            preserve_default=False,
        ),
    ]
