# Generated by Django 3.2.16 on 2022-11-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_teacher'),
        ('project_management', '0010_proposal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.teacher', verbose_name='Assigned By'),
        ),
    ]
