# Generated by Django 3.2.16 on 2022-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0013_auto_20221120_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='criteria_1',
            field=models.IntegerField(max_length=128, verbose_name='Criteria 1 Mark'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='criteria_2',
            field=models.IntegerField(max_length=128, verbose_name='Criteria 2 Mark'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='supervisor',
            field=models.IntegerField(max_length=128, verbose_name='Supervisor Mark'),
        ),
    ]
