# Generated by Django 3.2.16 on 2022-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_auto_20221122_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='criteria_1',
            field=models.IntegerField(verbose_name='Criteria 1 Mark'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='criteria_2',
            field=models.IntegerField(verbose_name='Criteria 2 Mark'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='supervisor',
            field=models.IntegerField(verbose_name='Supervisor Mark'),
        ),
    ]
