# Generated by Django 3.2.16 on 2022-11-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0017_alter_proposal_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_management.course'),
        ),
    ]
