# Generated by Django 3.2.16 on 2022-11-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0021_result_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='result',
            name='marks',
        ),
        migrations.AddField(
            model_name='marksheet',
            name='result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='project_management.result', verbose_name='Result'),
        ),
    ]
