# Generated by Django 3.2.16 on 2022-11-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0022_auto_20221124_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='student',
        ),
    ]
