# Generated by Django 3.2.16 on 2023-02-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20230207_2220'),
        ('project_management', '0029_auto_20221126_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='accounts.teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.teacher', verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assigned_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_proposals', to='accounts.teacher', verbose_name='Assigned Supervisor'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(upload_to='proposals/', verbose_name='Proposal File'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_submitted', to='accounts.student', verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.student', verbose_name='Team Lead'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='accounts.student', verbose_name='Student'),
        ),
    ]
