# Generated by Django 3.2.16 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0031_auto_20230207_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='RUNNING', max_length=32, verbose_name='State'),
        ),
    ]
