# Generated by Django 3.2.16 on 2023-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0033_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('CSE_3300', 'CSE 3300'), ('CSE_4800', 'CSE 4800'), ('CSE_4801', 'CSE 4801')], default='CSE_3300', max_length=32, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('Project I', 'CSE 3300'), ('Project II part I', 'CSE 4800'), ('Project II part II', 'CSE 4801')], default='Project I', max_length=32, verbose_name='Title'),
        ),
    ]
