# Generated by Django 3.2.16 on 2023-02-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0035_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('3300', 'CSE 3300'), ('4800', 'CSE 4800'), ('4801', 'CSE 4801')], default='3300', max_length=32, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('CSE 3300', 'Project I'), ('CSE 4800', 'Project II part I'), ('CSE 4801', 'Project II part II')], default='CSE 3300', max_length=32, verbose_name='Title'),
        ),
    ]
