# Generated by Django 3.2.16 on 2023-02-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20230207_2220'),
        ('project_management', '0038_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='assigned_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proposals', to='accounts.teacher', verbose_name='Assigned Supervisor'),
        ),
    ]
