# Generated by Django 3.2.16 on 2023-02-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0040_alter_proposal_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice', to='project_management.course', verbose_name='Course'),
        ),
    ]
