# Generated by Django 3.2.16 on 2023-02-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0041_alter_notice_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='course_code',
            field=models.CharField(choices=[('3300', 'CSE 3300'), ('4800', 'CSE 4800'), ('4801', 'CSE 4801')], default='3300', max_length=32, verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='notice',
            name='semester',
            field=models.CharField(blank=True, max_length=32, verbose_name='Semester'),
        ),
    ]
