# Generated by Django 3.2.16 on 2023-02-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0042_auto_20230217_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='course',
        ),
    ]
