# Generated by Django 3.2.16 on 2022-11-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full Name')),
                ('initials', models.CharField(max_length=20, verbose_name='Initials')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full Name')),
                ('student_id', models.CharField(max_length=30, verbose_name='Student Id')),
                ('batch', models.IntegerField(verbose_name='Batch')),
                ('section', models.CharField(max_length=10, verbose_name='Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
