# Generated by Django 3.2.16 on 2022-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=10, null=True, verbose_name='Section'),
        ),
    ]
